title: "orbitalflower"
description: "orbitalflower"
author: "orbitalflower"
defaultlicense: "CC BY"
hitcounterid: "107279"

permalink: none

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

category_emoji:
  comp: "ğŸ’»"
  etc: "ğŸ“¦"
  games: "ğŸ•¹ï¸"
  opinion: "ğŸ’¬"
  rpg: "ğŸ²"
  tv: "ğŸ“º"
